desc: Multinode HDP3 with HDF32 cluster for Personality Recognition Demo
seq:
- open_port: [-1, 1, 65534, '192.175.27.2/32']  # Hwx VPN
- open_port: [tcp, 22, 22, '0.0.0.0/0']
deploywait: 1800
purge: true
infra:
  ambarirepo:
    version: 2.7.1.0
    baseUrl: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.7.1.0
    gpgKeyUrl: http://public-repo-1.hortonworks.com/ambari/centos7/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins
  stackrepo:
    ver: 3.0.1.0-187
    url: http://public-repo-1.hortonworks.com/HDP/centos7/3.x/updates/3.0.1.0/HDP-3.0.1.0-187.xml
blueprint: 
	name: data-science-workshop-blueprint.json
recipe:
- name: init-metastores.sh
type: PRE_AMBARI_START